# Generated by Django 5.0.2 on 2024-03-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0003_billing_address_shipping_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='shop_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_size', models.CharField(max_length=5)),
                ('product_colour', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='shop_detail',
            name='product_colour',
        ),
        migrations.RemoveField(
            model_name='shop_detail',
            name='product_size',
        ),
    ]
