# Generated by Django 5.0.2 on 2024-03-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0004_shop_cart_remove_shop_detail_product_colour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_cart',
            name='product_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
