# Generated by Django 5.0.2 on 2024-03-02 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0006_shop_cart_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_cart',
            name='product_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.shop'),
        ),
    ]
