# Generated by Django 5.0.2 on 2024-03-04 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0009_category_alter_billing_address_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='category_id',
            new_name='category_name',
        ),
    ]
