# Generated by Django 5.0.2 on 2024-03-04 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0010_rename_category_id_shop_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='category_name',
            new_name='category_id',
        ),
    ]
